package models

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GeneratePresetINI creates a llama.cpp preset INI file from the model
// registry. Each model gets a section with per-model settings.
//
// Section names use the registry ID, which is unique per model (one entry
// per quant file). The earlier dirname-based scheme collided whenever a
// repo directory held multiple quants — INI sections sharing a name get
// merged by llama.cpp's parser, silently dropping every quant past the
// first. The aliases line still lists the dirname plus the public short
// name and any user aliases, so callers can address a model by any of them.
// The router runs with --models-preset only (no --models-dir), so we don't
// need the section name to match auto-discovery.
//
// INI keys map directly to llama-server CLI flags with leading dashes removed.
func GeneratePresetINI(modelsDir string, models []*Model, configs map[string]*ModelConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by llama-toolchest — do not edit manually.\n")
	b.WriteString("# Changes here will be overwritten when model configs are saved.\n\n")

	// Track which dirname-aliases collide across multiple models so we can
	// drop them from aliases entirely — listing the same alias on two
	// sections makes the router refuse to load whichever it sees second.
	dirCounts := map[string]int{}
	for _, m := range models {
		cfg, ok := configs[m.ID]
		if !ok || !cfg.Enabled {
			continue
		}
		if d := autoDiscoveryName(modelsDir, m.FilePath); d != "" {
			dirCounts[d]++
		}
	}

	for _, m := range models {
		cfg, ok := configs[m.ID]
		if !ok || !cfg.Enabled {
			continue
		}

		sectionName := m.ID

		b.WriteString(fmt.Sprintf("[%s]\n", sectionName))
		b.WriteString(fmt.Sprintf("model = %s\n", m.FilePath))

		// Aliases: every name a client might use to reference this model.
		// The dirname is included only when it's unique to this model — for
		// multi-quant repos it'd collide with sibling sections.
		seen := map[string]bool{}
		aliasList := []string{}
		add := func(a string) {
			if a == "" || seen[a] {
				return
			}
			seen[a] = true
			aliasList = append(aliasList, a)
		}
		add(sectionName)
		if dn := autoDiscoveryName(modelsDir, m.FilePath); dn != "" && dirCounts[dn] == 1 {
			add(dn)
		}
		add(m.PublicName())
		for _, a := range cfg.Aliases {
			add(a)
		}
		b.WriteString(fmt.Sprintf("alias = %s\n", strings.Join(aliasList, ",")))

		isEmbed := m.IsEmbedding()
		writeConfigParams(&b, cfg, isEmbed)
		b.WriteString("\n")
	}

	return b.String()
}

// autoDiscoveryName returns the name that --models-dir would assign to a
// model at the given path. Returns the first directory name under modelsDir.
func autoDiscoveryName(modelsDir, filePath string) string {
	rel, err := filepath.Rel(modelsDir, filePath)
	if err != nil {
		return ""
	}
	// rel is like "unsloth--Qwen3.5-27B-GGUF/Qwen3.5-27B-Q4_K_M.gguf"
	// or "unsloth--DeepSeek-R1-GGUF/UD-Q8_K_XL/model-00001.gguf"
	parts := strings.SplitN(rel, string(filepath.Separator), 2)
	if len(parts) == 0 {
		return ""
	}
	return parts[0]
}

func writeConfigParams(b *strings.Builder, cfg *ModelConfig, isEmbedding bool) {
	if !isEmbedding && cfg.ContextSize > 0 {
		b.WriteString(fmt.Sprintf("ctx-size = %d\n", cfg.ContextSize))
	}
	if cfg.BatchSize > 0 {
		b.WriteString(fmt.Sprintf("batch-size = %d\n", cfg.BatchSize))
	}
	if cfg.UBatchSize > 0 {
		b.WriteString(fmt.Sprintf("ubatch-size = %d\n", cfg.UBatchSize))
	}
	if cfg.GPULayers > 0 {
		b.WriteString(fmt.Sprintf("gpu-layers = %d\n", cfg.GPULayers))
	}
	if cfg.Threads > 0 {
		b.WriteString(fmt.Sprintf("threads = %d\n", cfg.Threads))
	}
	if cfg.Parallel > 1 {
		b.WriteString(fmt.Sprintf("parallel = %d\n", cfg.Parallel))
	}
	if cfg.TensorSplit != "" {
		b.WriteString(fmt.Sprintf("tensor-split = %s\n", cfg.TensorSplit))
	}
	if cfg.SplitMode != "" {
		b.WriteString(fmt.Sprintf("split-mode = %s\n", cfg.SplitMode))
	}
	if cfg.MainGPU > 0 {
		b.WriteString(fmt.Sprintf("main-gpu = %d\n", cfg.MainGPU))
	}
	if isEmbedding {
		b.WriteString("embeddings = true\n")
	}
	if !isEmbedding {
		if cfg.FlashAttention {
			b.WriteString("flash-attn = on\n")
		}
		if cfg.Jinja {
			b.WriteString("jinja = true\n")
		}
		if cfg.KVCacheQuant != "" {
			b.WriteString(fmt.Sprintf("cache-type-k = %s\n", cfg.KVCacheQuant))
			b.WriteString(fmt.Sprintf("cache-type-v = %s\n", cfg.KVCacheQuant))
		}
		if cfg.DirectIO {
			b.WriteString("direct-io = true\n")
		}
		if cfg.MmprojPath != "" && !cfg.MmprojDisabled {
			b.WriteString(fmt.Sprintf("mmproj = %s\n", cfg.MmprojPath))
		}
		// Speculative decoding (see specDecodingParams for the SpecType rules).
		for _, p := range specDecodingParams(cfg) {
			b.WriteString(fmt.Sprintf("%s = %s\n", p.Name, p.Value))
		}
	}

	// Sampling parameters
	if cfg.Temperature != nil {
		b.WriteString(fmt.Sprintf("temp = %g\n", *cfg.Temperature))
	}
	if cfg.TopP != nil {
		b.WriteString(fmt.Sprintf("top-p = %g\n", *cfg.TopP))
	}
	if cfg.TopK != nil {
		b.WriteString(fmt.Sprintf("top-k = %d\n", *cfg.TopK))
	}
	if cfg.MinP != nil {
		b.WriteString(fmt.Sprintf("min-p = %g\n", *cfg.MinP))
	}
	if cfg.PresencePenalty != nil {
		b.WriteString(fmt.Sprintf("presence-penalty = %g\n", *cfg.PresencePenalty))
	}
	if cfg.RepeatPenalty != nil {
		b.WriteString(fmt.Sprintf("repeat-penalty = %g\n", *cfg.RepeatPenalty))
	}

	// Extra flags. Parse shell-style so "--flag value" (space-separated) and
	// quoted values containing spaces survive intact. The old strings.Fields
	// split shredded "--reasoning-budget 4096 --msg \"a b c\"" into a pile of
	// bogus "4096 = true" / "b = true" keys (issue #67).
	for _, kv := range parseExtraFlags(cfg.ExtraFlags) {
		b.WriteString(fmt.Sprintf("%s = %s\n", kv.key, kv.value))
	}
}

type extraFlag struct {
	key   string
	value string
}

// parseExtraFlags tokenizes a raw extra-flags string the way a shell would —
// honoring single and double quotes so values containing spaces stay together —
// then pairs each "--flag" with its value. Both "--flag value" and
// "--flag=value" are accepted, and a flag with no following value becomes
// "true" (a boolean switch). Values are written verbatim into the INI; the
// llama.cpp preset parser reads the rest of the line, so spaces are fine.
func parseExtraFlags(raw string) []extraFlag {
	tokens := tokenizeFlags(raw)
	var out []extraFlag
	for i := 0; i < len(tokens); i++ {
		tok := tokens[i]
		if !strings.HasPrefix(tok, "-") {
			// A value with no preceding flag — nothing sensible to do, skip.
			continue
		}
		key := strings.TrimLeft(tok, "-")
		if key == "" {
			continue
		}
		if eq := strings.IndexByte(key, '='); eq >= 0 {
			out = append(out, extraFlag{key[:eq], key[eq+1:]})
			continue
		}
		// A following non-flag token is this flag's value. Negative numbers
		// (e.g. "-1") count as values, not flags.
		if i+1 < len(tokens) && !looksLikeFlag(tokens[i+1]) {
			out = append(out, extraFlag{key, tokens[i+1]})
			i++
			continue
		}
		out = append(out, extraFlag{key, "true"})
	}
	return out
}

// looksLikeFlag reports whether a token introduces a new flag rather than
// being a value. A leading dash followed by a digit or dot (e.g. "-1",
// "-.5") is treated as a negative-number value.
func looksLikeFlag(tok string) bool {
	if len(tok) < 2 || tok[0] != '-' {
		return false
	}
	c := tok[1]
	return !(c >= '0' && c <= '9') && c != '.'
}

// tokenizeFlags splits a command-line string into tokens, honoring single and
// double quotes (which are removed, their contents kept as part of the token).
// Whitespace outside quotes separates tokens.
func tokenizeFlags(raw string) []string {
	var tokens []string
	var cur strings.Builder
	inToken := false
	var quote rune // 0 when not inside quotes
	for _, r := range raw {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			} else {
				cur.WriteRune(r)
			}
		case r == '\'' || r == '"':
			quote = r
			inToken = true
		case r == ' ' || r == '\t' || r == '\n' || r == '\r':
			if inToken {
				tokens = append(tokens, cur.String())
				cur.Reset()
				inToken = false
			}
		default:
			cur.WriteRune(r)
			inToken = true
		}
	}
	if inToken {
		tokens = append(tokens, cur.String())
	}
	return tokens
}

// RouterName returns the model name that the llama.cpp router uses for
// load/unload operations. This is the INI section name written by
// GeneratePresetINI, which is now the registry ID — a unique-per-quant
// value. Aliases work for inference requests but NOT for /models/load
// and /models/unload, so callers wiring up explicit (un)load calls must
// use this name.
func (r *Registry) RouterName(id string) string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	if _, ok := r.data.Models[id]; !ok {
		return id
	}
	return id
}

// ModelFilePath returns the GGUF file path for a model.
func (r *Registry) ModelFilePath(id string) string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	m, ok := r.data.Models[id]
	if !ok {
		return ""
	}
	return m.FilePath
}

// PresetFileName is the preset the router normally runs against,
// regenerated from the registry on every start.
const PresetFileName = "preset.ini"

// BenchPresetFileName is a throwaway preset used when a benchmark job
// needs to run a model under config that differs from what the user
// saved. Written to a separate file so the real preset — and the
// models.json it derives from — are never touched: an interrupted job
// leaves nothing behind but a stale file nobody reads.
const BenchPresetFileName = "bench-preset.ini"

// WritePresetINI generates and writes the preset INI file to the data directory.
func (r *Registry) WritePresetINI() (string, error) {
	return r.writePreset(PresetFileName, nil)
}

// WriteBenchPresetINI writes a preset in which the given models run
// under substitute configs, leaving every other model at its saved
// config. Keys are registry IDs; unknown IDs are ignored.
//
// Callers must treat the returned path as ephemeral: the router has to
// be restarted to pick it up, and restarted again against
// WritePresetINI's output to go back to the user's settings.
func (r *Registry) WriteBenchPresetINI(overrides map[string]*ModelConfig) (string, error) {
	return r.writePreset(BenchPresetFileName, overrides)
}

func (r *Registry) writePreset(name string, overrides map[string]*ModelConfig) (string, error) {
	r.mu.RLock()
	models := make([]*Model, 0, len(r.data.Models))
	for _, m := range r.data.Models {
		models = append(models, m)
	}
	// Sort by ID so the generated file is byte-stable across writes.
	// Ranging a map alone left section order random, which made presets
	// undiffable and meant two presets built from identical config could
	// not be compared byte-wise.
	sort.Slice(models, func(i, j int) bool { return models[i].ID < models[j].ID })
	// Shallow-copy the config map so an override can be swapped in
	// without mutating the registry's own pointers — GeneratePresetINI
	// only reads, but the registry map is shared with live handlers.
	configs := make(map[string]*ModelConfig, len(r.data.Configs))
	for id, cfg := range r.data.Configs {
		configs[id] = cfg
	}
	r.mu.RUnlock()

	for id, cfg := range overrides {
		if cfg == nil {
			continue
		}
		if _, known := configs[id]; !known {
			continue
		}
		configs[id] = cfg
	}

	content := GeneratePresetINI(r.modelsDir, models, configs)

	presetPath := filepath.Join(r.dataDir, "config", name)
	os.MkdirAll(filepath.Dir(presetPath), 0o755)

	if err := os.WriteFile(presetPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write preset: %w", err)
	}

	slog.Debug("wrote preset", "path", presetPath,
		"models", len(models), "substituted", len(overrides))

	return presetPath, nil
}
