package models

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GeneratePresetINI creates a llama.cpp preset INI file from the model
// registry. Each model with a config gets a section with per-model
// settings. Returns the INI content as a string.
//
// INI keys map directly to llama-server CLI flags with leading dashes removed.
// See: https://github.com/ggerganov/llama.cpp/blob/master/tools/server/README.md
func GeneratePresetINI(models []*Model, configs map[string]*ModelConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by llamactl — do not edit manually.\n")
	b.WriteString("# Changes here will be overwritten when model configs are saved.\n\n")

	for _, m := range models {
		cfg, ok := configs[m.ID]
		if !ok {
			continue
		}

		b.WriteString(fmt.Sprintf("[%s]\n", m.ID))
		b.WriteString(fmt.Sprintf("model = %s\n", m.FilePath))
		b.WriteString(fmt.Sprintf("alias = %s\n", m.ID))

		if cfg.ContextSize > 0 {
			b.WriteString(fmt.Sprintf("ctx-size = %d\n", cfg.ContextSize))
		}
		if cfg.GPULayers > 0 {
			b.WriteString(fmt.Sprintf("gpu-layers = %d\n", cfg.GPULayers))
		}
		if cfg.Threads > 0 {
			b.WriteString(fmt.Sprintf("threads = %d\n", cfg.Threads))
		}
		if cfg.TensorSplit != "" {
			b.WriteString(fmt.Sprintf("tensor-split = %s\n", cfg.TensorSplit))
		}
		if cfg.FlashAttention {
			b.WriteString("flash-attn = on\n")
		}
		if cfg.Jinja {
			b.WriteString("jinja = true\n")
		}
		if cfg.KVCacheQuant != "" {
			b.WriteString(fmt.Sprintf("cache-type-k = %s\n", cfg.KVCacheQuant))
			b.WriteString(fmt.Sprintf("cache-type-v = %s\n", cfg.KVCacheQuant))
		}
		if cfg.DirectIO {
			b.WriteString("direct-io = true\n")
		}

		// Sampling parameters
		if cfg.Temperature != nil {
			b.WriteString(fmt.Sprintf("temp = %g\n", *cfg.Temperature))
		}
		if cfg.TopP != nil {
			b.WriteString(fmt.Sprintf("top-p = %g\n", *cfg.TopP))
		}
		if cfg.TopK != nil {
			b.WriteString(fmt.Sprintf("top-k = %d\n", *cfg.TopK))
		}
		if cfg.MinP != nil {
			b.WriteString(fmt.Sprintf("min-p = %g\n", *cfg.MinP))
		}
		if cfg.PresencePenalty != nil {
			b.WriteString(fmt.Sprintf("presence-penalty = %g\n", *cfg.PresencePenalty))
		}
		if cfg.RepeatPenalty != nil {
			b.WriteString(fmt.Sprintf("repeat-penalty = %g\n", *cfg.RepeatPenalty))
		}

		// Extra flags — parse as key=value or key pairs
		if cfg.ExtraFlags != "" {
			for _, flag := range strings.Fields(cfg.ExtraFlags) {
				flag = strings.TrimLeft(flag, "-")
				if parts := strings.SplitN(flag, "=", 2); len(parts) == 2 {
					b.WriteString(fmt.Sprintf("%s = %s\n", parts[0], parts[1]))
				} else {
					b.WriteString(fmt.Sprintf("%s = true\n", flag))
				}
			}
		}

		b.WriteString("\n")
	}

	return b.String()
}

// WritePresetINI generates and writes the preset INI file to the data directory.
// Returns the path to the written file.
func (r *Registry) WritePresetINI() (string, error) {
	r.mu.RLock()
	models := make([]*Model, 0, len(r.data.Models))
	for _, m := range r.data.Models {
		models = append(models, m)
	}
	configs := r.data.Configs
	r.mu.RUnlock()

	content := GeneratePresetINI(models, configs)

	presetPath := filepath.Join(r.dataDir, "config", "preset.ini")
	os.MkdirAll(filepath.Dir(presetPath), 0o755)

	if err := os.WriteFile(presetPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write preset: %w", err)
	}

	return presetPath, nil
}
