# scripts/lib/host.sh
#
# Host install logic — installs llama-toolchest directly on the host system
# rather than inside a container. Sourced by setup.sh; depends on common
# helpers (log/ok/warn/err/prompt_confirm) and on scripts/lib/service.sh.
#
# Strategy: build the binary from source via `go build`. Once a tagged
# release exists on GitHub, this can switch to fetching the prebuilt
# package; until then, from-source is the only working path.
#
# Layout (Linux):
#   user install (default)
#     binary:   ~/.local/bin/llama-toolchest
#     config:   $XDG_CONFIG_HOME/llama-toolchest/llama-toolchest.yaml
#     data:     $XDG_DATA_HOME/llama-toolchest
#     unit:     ~/.config/systemd/user/llama-toolchest.service
#   system install (root)
#     binary:   /usr/local/bin/llama-toolchest
#     config:   /etc/llama-toolchest/llama-toolchest.yaml
#     data:     /var/lib/llama-toolchest
#     unit:     /etc/systemd/system/llama-toolchest.service
#
# Public functions:
#   host_install
#   host_uninstall
#   host_status

host_scope() {
    if [[ $EUID -eq 0 ]]; then
        echo "system"
    else
        echo "user"
    fi
}

host_bin_dir() {
    if [[ "$(host_scope)" == "system" ]]; then
        echo "/usr/local/bin"
    else
        echo "${HOME}/.local/bin"
    fi
}

host_config_dir() {
    if [[ "$(host_scope)" == "system" ]]; then
        echo "/etc/llama-toolchest"
    else
        echo "${XDG_CONFIG_HOME:-$HOME/.config}/llama-toolchest"
    fi
}

host_data_dir() {
    if [[ "$(host_scope)" == "system" ]]; then
        echo "/var/lib/llama-toolchest"
    else
        echo "${XDG_DATA_HOME:-$HOME/.local/share}/llama-toolchest"
    fi
}

host_binary_path() {
    echo "$(host_bin_dir)/llama-toolchest"
}

host_config_path() {
    echo "$(host_config_dir)/llama-toolchest.yaml"
}

# Verify that the prerequisites for an in-tree `go build` are present. Does
# not install anything — leaves that to the user, since the build toolchain
# differs by distro and the existing setup.sh prereq logic already handles
# it for the container path.
host_check_build_toolchain() {
    local missing=()
    command -v go      >/dev/null 2>&1 || missing+=("go (>= 1.25)")
    command -v cmake   >/dev/null 2>&1 || missing+=("cmake")
    command -v ninja   >/dev/null 2>&1 || command -v ninja-build >/dev/null 2>&1 || missing+=("ninja-build")
    command -v git     >/dev/null 2>&1 || missing+=("git")

    if [[ ${#missing[@]} -gt 0 ]]; then
        warn "Missing build prerequisites: ${missing[*]}"
        log "These are needed to build the llama-toolchest binary and (later) llama.cpp from the UI."
        log "Install via your package manager:"
        echo "    Debian/Ubuntu:  sudo apt-get install golang cmake ninja-build git build-essential"
        echo "    Fedora:         sudo dnf install golang cmake ninja-build git gcc-c++ make"
        echo "    Arch:           sudo pacman -S go cmake ninja git base-devel"
        return 1
    fi
    return 0
}

host_build_binary() {
    local out; out="$(host_binary_path)"
    local commit; commit="$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    local ver="dev-$commit"
    local date; date="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    log "Building llama-toolchest from source ($ver)..."
    mkdir -p "$(dirname "$out")"
    (cd "$SCRIPT_DIR" && \
        go build \
            -ldflags="-s -w -X main.version=$ver -X main.commit=$commit -X main.date=$date" \
            -o "$out" \
            ./cmd/llama-toolchest)
    ok "Installed binary: $out"
}

# Write the example config to the user's config dir if it doesn't exist.
# Existing configs are left alone — we don't overwrite the user's settings.
host_write_config() {
    local cfg_path; cfg_path="$(host_config_path)"
    local cfg_dir; cfg_dir="$(host_config_dir)"
    local data_dir; data_dir="$(host_data_dir)"

    mkdir -p "$cfg_dir" "$data_dir/builds" "$data_dir/models" "$data_dir/config"

    if [[ -f "$cfg_path" ]]; then
        log "Config already exists at $cfg_path — leaving it alone."
        return 0
    fi

    log "Writing config: $cfg_path"
    cat > "$cfg_path" <<EOF
# llama-toolchest configuration (host install, $(host_scope) scope)
# Generated by setup.sh — edit this file or use the Settings UI.

listen_addr: ":${LLAMA_TOOLCHEST_PORT:-3000}"
data_dir: "$data_dir"
llama_port: ${LLAMA_TOOLCHEST_INFERENCE_PORT:-8080}
external_url: "http://localhost:${LLAMA_TOOLCHEST_PORT:-3000}"
log_level: "info"
models_max: 1
auto_start: false
EOF
}

# Write a systemd drop-in override carrying GPU env vars (e.g.
# HSA_OVERRIDE_GFX_VERSION) and the explicit --config path. This way the
# packaged unit file stays generic and per-machine knobs go in the override.
host_write_unit_override() {
    local scope; scope="$(service_scope)"
    local override_dir
    if [[ "$scope" == "system" ]]; then
        override_dir="/etc/systemd/system/llama-toolchest.service.d"
    else
        override_dir="${HOME}/.config/systemd/user/llama-toolchest.service.d"
    fi

    mkdir -p "$override_dir"
    local override_file="$override_dir/override.conf"

    {
        echo "[Service]"
        echo "ExecStart="
        echo "ExecStart=$(host_binary_path) --config $(host_config_path)"
        if [[ -n "${AMD_GFX_VERSION:-}" ]]; then
            echo "Environment=HSA_OVERRIDE_GFX_VERSION=${AMD_GFX_VERSION}"
        fi
    } > "$override_file"

    log "Wrote unit override: $override_file"
}

host_install() {
    log "Host install — scope: $(host_scope)"
    echo ""

    if ! host_check_build_toolchain; then
        err "Resolve missing build prerequisites and re-run."
        return 1
    fi

    # Build + install the binary.
    host_build_binary

    # Verify the bin dir is on PATH (user install only — system /usr/local/bin
    # is always on PATH).
    if [[ "$(host_scope)" == "user" ]] && ! echo ":$PATH:" | grep -q ":$(host_bin_dir):"; then
        warn "$(host_bin_dir) is not on your PATH."
        log "Add it to your shell rc (e.g. ~/.bashrc or ~/.zshrc):"
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo ""
    fi

    # Config skeleton.
    host_write_config

    # Systemd unit + override.
    local unit_src="$SCRIPT_DIR/packaging/systemd/llama-toolchest.service"
    if [[ "$(host_scope)" == "user" ]]; then
        unit_src="$SCRIPT_DIR/packaging/systemd/llama-toolchest.user.service"
    fi
    service_install "$unit_src"
    host_write_unit_override

    # If the service is already running, this is a re-install — restart so
    # the new binary takes effect. Otherwise prompt to enable+start fresh.
    if service_is_active; then
        if prompt_confirm "Service is already running. Restart to pick up the new binary?"; then
            service_restart
            ok "llama-toolchest service restarted"
        else
            warn "New binary on disk but service still running the old version. Restart manually with:"
            if [[ "$(host_scope)" == "user" ]]; then
                echo "    systemctl --user restart llama-toolchest"
            else
                echo "    sudo systemctl restart llama-toolchest"
            fi
        fi
    elif prompt_confirm "Enable and start the service now?"; then
        service_enable
        ok "llama-toolchest service enabled and started"
    else
        log "Service installed but not enabled. Start later with:"
        if [[ "$(host_scope)" == "user" ]]; then
            echo "    systemctl --user start llama-toolchest"
        else
            echo "    sudo systemctl start llama-toolchest"
        fi
    fi

    echo ""
    ok "Host install complete."
    echo ""
    echo "  Binary:      $(host_binary_path)"
    echo "  Config:      $(host_config_path)"
    echo "  Data dir:    $(host_data_dir)"
    echo "  Web UI:      http://localhost:${LLAMA_TOOLCHEST_PORT:-3000}"
    echo ""
}

host_uninstall() {
    log "Uninstalling host install — scope: $(host_scope)"

    service_uninstall

    local override_dir
    if [[ "$(service_scope)" == "system" ]]; then
        override_dir="/etc/systemd/system/llama-toolchest.service.d"
    else
        override_dir="${HOME}/.config/systemd/user/llama-toolchest.service.d"
    fi
    [[ -d "$override_dir" ]] && rm -rf "$override_dir"

    local bin; bin="$(host_binary_path)"
    if [[ -f "$bin" ]]; then
        rm -f "$bin"
        log "Removed: $bin"
    fi

    local data_dir; data_dir="$(host_data_dir)"
    local cfg_dir; cfg_dir="$(host_config_dir)"
    log "Config dir ($cfg_dir) and data dir ($data_dir) preserved (contains your models and builds)."
    if prompt_confirm "Also remove config and data dirs? This DELETES all downloaded models and llama.cpp builds."; then
        rm -rf "$cfg_dir" "$data_dir"
        log "Removed config and data dirs."
    fi

    ok "Host uninstall complete."
}

host_status() {
    echo "Scope:       $(host_scope)"
    echo "Binary:      $(host_binary_path)$( [[ -x "$(host_binary_path)" ]] && echo "" || echo "  (not installed)")"
    echo "Config:      $(host_config_path)$( [[ -f "$(host_config_path)" ]] && echo "" || echo "  (missing)")"
    echo "Data dir:    $(host_data_dir)"
    echo "Service:     $(service_unit_path)"
    echo ""
    service_status
}
