package agentconfig

import (
	"encoding/json"
	"strings"
	"testing"
	"time"
)

var sample = Input{
	BaseURL: "http://gpu-box:3000/v1",
	Models: []Model{
		{ID: "Qwen3.6-27B-UD-Q4_K_XL", Context: 65536, MaxOutput: 16384, Tools: true, Reasoning: true},
		{ID: "gemma-4-12b-it-UD-Q6_K_XL", Context: 32768, MaxOutput: 8192, Tools: true, Vision: true},
	},
	GeneratedAt: time.Date(2026, 10, 9, 12, 0, 0, 0, time.UTC),
}

func withKey(in Input) Input { in.APIKey = true; return in }

func generate(t *testing.T, id string, in Input) string {
	t.Helper()
	a, ok := Find(id)
	if !ok {
		t.Fatalf("no agent %q", id)
	}
	b, err := a.Generate(in)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func decode(t *testing.T, s string) map[string]any {
	t.Helper()
	var v map[string]any
	if err := json.Unmarshal([]byte(s), &v); err != nil {
		t.Fatalf("not JSON: %v\n%s", err, s)
	}
	return v
}

// dig walks nested maps by key.
func dig(t *testing.T, v any, keys ...string) any {
	t.Helper()
	for _, k := range keys {
		m, ok := v.(map[string]any)
		if !ok {
			t.Fatalf("at %q: not an object: %v", k, v)
		}
		v = m[k]
	}
	return v
}

func TestMaxOutputFor(t *testing.T) {
	for ctx, want := range map[int]int{65536: 16384, 262144: 32768, 2048: 1024, 0: 1024} {
		if got := MaxOutputFor(ctx); got != want {
			t.Errorf("MaxOutputFor(%d) = %d, want %d", ctx, got, want)
		}
	}
}

func TestOpenCode(t *testing.T) {
	v := decode(t, generate(t, "opencode", sample))
	p := dig(t, v, "provider", ProviderID)
	if dig(t, p, "npm") != "@ai-sdk/openai-compatible" || dig(t, p, "options", "baseURL") != sample.BaseURL {
		t.Errorf("provider: %v", p)
	}
	if dig(t, p, "options", "apiKey") != "none" {
		t.Errorf("no-key placeholder: %v", dig(t, p, "options", "apiKey"))
	}
	q := dig(t, p, "models", "Qwen3.6-27B-UD-Q4_K_XL")
	if dig(t, q, "limit", "context") != 65536.0 || dig(t, q, "limit", "output") != 16384.0 ||
		dig(t, q, "tool_call") != true || dig(t, q, "reasoning") != true || dig(t, q, "attachment") != false {
		t.Errorf("qwen: %v", q)
	}
	g := dig(t, p, "models", "gemma-4-12b-it-UD-Q6_K_XL")
	if in := dig(t, g, "modalities", "input").([]any); len(in) != 2 || in[1] != "image" {
		t.Errorf("gemma modalities: %v", in)
	}
	if v["model"] != ProviderID+"/Qwen3.6-27B-UD-Q4_K_XL" || v["$schema"] == nil {
		t.Errorf("default model / schema: %v %v", v["model"], v["$schema"])
	}

	k := decode(t, generate(t, "opencode", withKey(sample)))
	if got := dig(t, k, "provider", ProviderID, "options", "apiKey"); got != "{env:"+KeyEnv+"}" {
		t.Errorf("key reference: %v", got)
	}
}

// Kilo is the opencode format without opencode's schema URL.
func TestKilo(t *testing.T) {
	v := decode(t, generate(t, "kilo", sample))
	if _, ok := v["$schema"]; ok {
		t.Error("kilo file carries opencode's $schema")
	}
	if dig(t, v, "provider", ProviderID, "options", "baseURL") != sample.BaseURL {
		t.Errorf("kilo: %v", v)
	}
}

func TestPi(t *testing.T) {
	v := decode(t, generate(t, "pi", sample))
	p := dig(t, v, "providers", ProviderID)
	if dig(t, p, "api") != "openai-completions" || dig(t, p, "baseUrl") != sample.BaseURL || dig(t, p, "apiKey") != "none" {
		t.Errorf("provider: %v", p)
	}
	ms := dig(t, p, "models").([]any)
	if len(ms) != 2 || dig(t, ms[0], "id") != "Qwen3.6-27B-UD-Q4_K_XL" ||
		dig(t, ms[0], "contextWindow") != 65536.0 || dig(t, ms[0], "maxTokens") != 16384.0 {
		t.Errorf("models: %v", ms)
	}
	if got := dig(t, decode(t, generate(t, "pi", withKey(sample))), "providers", ProviderID, "apiKey"); got != "$"+KeyEnv {
		t.Errorf("key reference: %v", got)
	}
}

func TestGoose(t *testing.T) {
	v := decode(t, generate(t, "goose", sample))
	if v["base_url"] != "http://gpu-box:3000/v1/chat/completions" || v["engine"] != "openai" || v["requires_auth"] != false {
		t.Errorf("goose: %v", v)
	}
	if _, ok := v["api_key_env"]; ok {
		t.Error("api_key_env set without a key")
	}
	if ms := v["models"].([]any); dig(t, ms[1], "context_limit") != 32768.0 {
		t.Errorf("models: %v", ms)
	}
	k := decode(t, generate(t, "goose", withKey(sample)))
	if k["api_key_env"] != KeyEnv || k["requires_auth"] != true {
		t.Errorf("with key: %v", k)
	}
}

func TestCrush(t *testing.T) {
	s := generate(t, "crush", sample)
	for _, want := range []string{
		"# Generated by llama-toolchest on 2026-10-09 12:00 UTC.",
		`provider add llama-toolchest --name "llama-toolchest" --type openai-compat`,
		`--base-url "http://gpu-box:3000/v1" --api-key "none"`,
		`model add llama-toolchest/gemma-4-12b-it-UD-Q6_K_XL --name "gemma-4-12b-it-UD-Q6_K_XL"`,
		"--context-window 32768 --default-max-tokens 8192 --can-reason false --supports-images true",
		"model large llama-toolchest/Qwen3.6-27B-UD-Q4_K_XL",
		"option request-timeout 600",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("crushrc lacks %q:\n%s", want, s)
		}
	}
	if !strings.Contains(generate(t, "crush", withKey(sample)), `--api-key "${`+KeyEnv+`}"`) {
		t.Error("crushrc does not read the key from the environment")
	}
}

// No file ever carries a key, only the variable that holds it.
func TestNoAgentWritesAKey(t *testing.T) {
	for _, a := range Agents {
		out := generate(t, a.ID, withKey(sample))
		if !strings.Contains(out, KeyEnv) {
			t.Errorf("%s: with a key set, the file does not refer to %s", a.ID, KeyEnv)
		}
	}
}

// Every agent says where its file goes on every OS.
func TestAgentsDescribeSetup(t *testing.T) {
	for _, a := range Agents {
		if a.FileName == "" || a.Homepage == "" {
			t.Errorf("%s: missing file name or homepage", a.ID)
		}
		for _, os := range []OS{Linux, MacOS, Windows} {
			if a.SavePath[os] == "" {
				t.Errorf("%s: no %s path", a.ID, os)
			}
		}
	}
}
