// Package agentconfig writes ready-to-use config files that point coding
// agents (opencode, Kilo Code, pi, Goose, Crush) at this server's
// OpenAI-compatible endpoint, listing the models it serves.
//
// Each agent wants the same facts in its own format: the base URL, how to
// find the API key, and per model the ID clients send, how much context one
// conversation gets, a max output, and whether it handles tools, images and
// reasoning. Without them an agent either can't see local models at all or
// compacts against the wrong context size, so the files are generated from
// what the server is serving now rather than written by hand.
//
// A generated file is a snapshot: change which models are served, or their
// context, and it has to be downloaded again. Formats that allow comments
// say so in a header.
package agentconfig

import (
	"fmt"
	"strings"
	"time"
)

// ProviderID names the provider in every agent's config, and KeyEnv is the
// environment variable the files read the API key from. The key itself is
// never written into a file: it would then sit in a download, and the
// variable keeps working when the key changes.
const (
	ProviderID   = "llama-toolchest"
	ProviderName = "llama-toolchest"
	KeyEnv       = "LLAMA_TOOLCHEST_API_KEY"
)

// Model is one served model as an agent sees it.
type Model struct {
	// ID is what clients send as "model": the public name /v1/models lists.
	ID string
	// Context is the most one conversation can use, which is what an agent
	// compacts against — not the whole pool when parallel slots split it.
	Context   int
	MaxOutput int
	Tools     bool
	Vision    bool
	Reasoning bool
}

// Input is everything a generator needs.
type Input struct {
	// BaseURL is the OpenAI-compatible root, ending in /v1.
	BaseURL string
	// APIKey is true when the server requires a key. The files then read it
	// from KeyEnv; otherwise they carry a placeholder, since several agents
	// hide a provider whose key is empty.
	APIKey bool
	// Models in order; the first is the default.
	Models      []Model
	GeneratedAt time.Time
}

// MaxOutputFor is the max output a model is given: a quarter of the
// conversation's context, capped at 32K. llama-server sets no limit of its
// own, but agents want a number, and one that leaves most of the context for
// the conversation itself.
func MaxOutputFor(context int) int {
	out := context / 4
	if out > 32768 {
		out = 32768
	}
	if out < 1024 {
		out = 1024
	}
	return out
}

// OS is a platform the setup steps cover.
type OS string

const (
	Linux   OS = "Linux"
	MacOS   OS = "macOS"
	Windows OS = "Windows"
)

// Agent is one supported coding agent.
type Agent struct {
	// ID is the URL slug: /api/agent-configs/{ID}.
	ID   string
	Name string
	// Homepage links the agent's own docs from the modal.
	Homepage string
	// FileName is what the download saves as.
	FileName string
	// SavePath is where the file goes, per OS. A path ending in "/" is a
	// directory the file is saved into.
	SavePath map[OS]string
	// Activate is what to run or add once the file is saved; empty when
	// saving it is enough.
	Activate string
	// Notes are short caveats shown under the steps.
	Notes []string
	// Generate writes the file.
	Generate func(Input) ([]byte, error)
}

// Agents is every supported agent, in the order the modal lists them.
var Agents = []Agent{opencode, kilo, pi, goose, crush}

// Find returns the agent with the given ID.
func Find(id string) (Agent, bool) {
	for _, a := range Agents {
		if a.ID == id {
			return a, true
		}
	}
	return Agent{}, false
}

// header is the comment a commentable format opens with.
func header(in Input, comment string) string {
	var b strings.Builder
	line := func(s string) { b.WriteString(strings.TrimRight(comment+" "+s, " ") + "\n") }
	line("Generated by llama-toolchest on " + in.GeneratedAt.Format("2006-01-02 15:04 MST") + ".")
	line("It lists the models the server was serving then; download it again")
	line("after changing which models are served or their context size.")
	line("")
	for _, m := range in.Models {
		line(fmt.Sprintf("  %s  (context %d)", m.ID, m.Context))
	}
	return b.String()
}
